[package]
name = "blackbird-state"
version = "0.1.0"
edition = "2024"

[dependencies]
blackbird-subsonic = { path = "../blackbird-subsonic" }
icu_collator = "2.0.0"

serde = { workspace = true }
smol_str = { version = "0.3.5", features = ["serde"] }
