[package]
name = "blackbird-client-shared"
version = "0.1.0"
edition = "2024"

[features]
media-controls = ["dep:souvlaki"]

[dependencies]
blackbird-core = { path = "../blackbird-core", default-features = false }
blackbird-shared = { path = "../blackbird-shared" }

serde = { workspace = true }
tracing = { workspace = true }
souvlaki = { version = "0.8.3", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = ["Win32_System_Console"] }
