[package]
name = "blackbird-client-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
blackbird-core = { path = "../blackbird-core", default-features = false }
blackbird-shared = { path = "../blackbird-shared" }

serde = { workspace = true }
